version: '3'
services:
  bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URI=${DATABASE_URI}
    volumes:
      - ./DOWNLOADS:/app/DOWNLOADS
    restart: unless-stopped